### ISSUE TITLE
GUI Mockups

### ISSUE THREAD

**Issue by pturon** [SoftwareprojektGR4/Organisation#5]
- Konfiguration
- Hauptmenü 
- Bestehende Spiele herunterladen / kopieren 
- Eigene Spiele
- Spiel beitreten 
- Login / Registrierung

**Comment by nloetkemann** [comment]
- Bei Spiel beitreten: mehr Informationen zum Spiel, wie viele Personen sind drin, ist das spiel passwort geschützt?

- Bei Spiel hosten: neues Fenster mit erstell-Optionen, passwort setzen, anzahl personen, name

- neue Profilübersicht: user löschen, abmelden, bearbeiten

- bei Spielliste(Lobby): suchen nach name, filter mit eingenen spielen vollen lobbys, chat mit anderen

- Namen vereinheitlichen

- Für den Spieleditor die Mockups erstellen, nach den Use-Case, mit hilfe button

**Comment by nloetkemann** [comment]
@pturon kannst du mal rein schauen und gucken, ob das bisher so passt?
Ich habe jetzt die punkte oben bis auf den editor germacht

**Comment by nloetkemann** [comment]
Würfel bei Editor hinzufügen.
Popups beim Editor für neue Karte/neues Feld/neue Aktion wie soll das aussehen? welche felder brauchen wir
Integration von Spielregeln, an welcher Stelle soll man sie erstzen.

**Comment by nloetkemann** [comment]
beschreibung raus bei hosten
editor min anzahl benutzer
prompt für mehr optionen beim erstellen
überschrift beim editor
editor suchen filter dropdown, bild an der rechten seite als vorschau
in einstellungen verbindung zu vr,echo
editor vr aktivieren
lobby mit echo
überschrift ändern in spiel beitreten in lobby ändern
spiele beitreten eigene löschen
neues mockup als spielleiter und als benutzer mit chat
